Repository dogukanarslan/SWE574-Group-3, pull requests merged in 2023-05, with the labels that each got.

#87 add report button
  app/feed/admin.py
  app/feed/migrations/0009_report.py
  app/feed/migrations/0010_report_description.py
  app/feed/models.py
  app/feed/serializers.py
  app/feed/views.py
  app/frontend/templates/_post.html
  app/frontend/templates/_postSpace.html
  app/frontend/templates/postDetail.html
Labels: enhancement

#97 delete myenv files
  app/myenv/Scripts/Activate.ps1
  app/myenv/Scripts/activate
  app/myenv/Scripts/activate.bat
  app/myenv/Scripts/deactivate.bat
  app/myenv/Scripts/pip.exe
  app/myenv/Scripts/pip3.10.exe
  app/myenv/Scripts/pip3.11.exe
  app/myenv/Scripts/pip3.exe
  app/myenv/Scripts/python.exe
  app/myenv/Scripts/python_d.exe
  app/myenv/Scripts/pythonw.exe
  app/myenv/Scripts/pythonw_d.exe
  app/myenv/pyvenv.cfg
Labels: maintenance

#98 Fix incorrect model name
  app/feed/views.py
Labels: bug

#83 margin is added for create space and create post
  app/frontend/templates/posts.html
  app/frontend/templates/spaces.html
Labels: enhancement

#100 context is converted to "@context"
  app/feed/serializers.py
Labels: feature

#101 Enhancement/platform description
  app/frontend/templates/editPost.html
  app/frontend/templates/postDetail.html
  app/frontend/templates/posts.html
  app/frontend/templates/spacePosts.html
  app/user/serializers.py
Labels: enhancement

#103 Add image annotations
  app/feed/migrations/0002_auto_20230524_2118.py
  app/feed/models.py
  app/feed/routers.py
  app/feed/serializers.py
  app/feed/urls.py
  app/feed/views.py
  app/frontend/templates/postDetail.html
Labels: feature

#102 Placeholder brought back for non-semantic tag
  app/frontend/templates/posts.html
Labels: issues, deployment, risk: low

#106 Reset ul inner html
  app/frontend/templates/postDetail.html
Labels: bug

#108 Move incorrect password logic into view
  app/user/serializers.py
  app/user/views.py
Labels: feature

#111 Create README.md
  README.md
Labels: documentation

#112 Redirect to related route
  app/feed/views.py
Labels: feature

#114 Fix typo
  README.md
Labels: documentation

#115 Name Update README.md
  README.md
Labels: documentation

#117 Delete unnecessary elements
  app/frontend/templates/follower.html
Labels: bug

#118 Bug fix/default badge object creation
  app/user/serializers.py
  app/user/tests.py
Labels: bug

#119 Convert json file into yaml
  app/fixtures/dump_db.json
  app/fixtures/dump_db.yaml
Labels: feature

#121 Update dump db
  app/fixtures/dump_db.yaml
Labels: enhancement

#125 bug fix for search combinations
  app/feed/views.py
Labels: bug

#124 bug fix for searching moderator
  app/feed/views.py
Labels: bug, priority: high, effort: low

#126 Adding semantic search and bugfix for multiple search
  app/feed/views.py
  app/frontend/templates/search.html
Labels: enhancement, priority: high

#127 Update README.md
  README.md
Labels: documentation

#133 Delete duplicate labels
  app/frontend/templates/postDetail.html
Labels: enhancement
