Repository dogukanarslan/SWE574-Group-3, pull requests merged in 2023-04, with the labels that each got.

#54 Check post link before creation
  app/feed/views.py
  app/frontend/templates/posts.html
Labels: enhancement

#55 Enhancement/add user search
  app/app/settings.py
  app/feed/tests.py
  app/feed/views.py
  app/frontend/static/index.css
  app/frontend/templates/profilePage.html
  app/user/migrations/0004_auto_20230404_1357.py
  app/user/models.py
  app/user/serializers.py
  app/user/views.py
Labels: enhancement

#61 Populate database with dummy data
  app/app/settings.py
  app/fixtures/dump_db.json
Labels: enhancement

#62 Enhancement/post feedback
  app/feed/migrations/0007_auto_20230411_2215.py
  app/feed/models.py
  app/feed/serializers.py
  app/fixtures/dump_db.json
  app/frontend/static/index.css
  app/static/default_post_image.png
Labels: enhancement

#65 Improvement/improve post detail design
  app/frontend/templates/ownPostDetail.html
  app/frontend/templates/postDetail.html
Labels: enhancement

#67 Unify postDetail and ownPostDetail html files
  app/feed/views.py
  app/frontend/templates/ownPostDetail.html
  app/frontend/templates/postDetail.html
Labels: bug, enhancement

#70 Redirect after adding a new comment
  app/feed/views.py
Labels: bug, feature

#72 Format comment date
  app/feed/serializers.py
Labels: enhancement

#74 Delete null field which conflicts with default field
  app/feed/migrations/0008_auto_20230423_1308.py
  app/feed/models.py
Labels: bug

#75 Enhancement/add text annotations
  app/feed/serializers.py
  app/feed/views.py
  app/fixtures/dump_db.json
  app/frontend/static/index.css
  app/frontend/templates/base.html
  app/frontend/templates/postDetail.html
Labels: enhancement
